builds:
  - id: gh-pr-comment
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gh-pr-comment/main.go
    binary: gh-pr-comment
    ldflags:
      - "-s -w"
  - id: gh-pr-upload
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gh-pr-upload/main.go
    binary: gh-pr-upload
    ldflags:
      - "-s -w"
archives:
  - builds:
      - gh-pr-comment
      - gh-pr-upload
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - gh-pr-comment-env.sh
before:
  hooks:
    - cp env.sh gh-pr-comment-env.sh
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--no-tty"
      - "--passphrase={{ .Env.SIGN_KEY_PASSPHRESE }}"
      - "--pinentry-mode=loopback"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  extra_files:
    - glob: ./install.sh
    - glob: ./install.sh.sig
    - glob: ./env.sh
    - glob: ./env.sh.sig
