dist: focal
language: go
go: 1.14
branches:
  only:
    - master
    - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"

addons:
  apt:
    packages:
      - upx-ucl

env:
  global:
    - CGO_ENABLED=0

install:
  - go build -ldflags="-s -w" ./cmd/gh-pr-comment
  - upx ./gh-pr-comment

script:
  - go vet ./...
  - go test ./...
  - .ci/upload-test.sh
