dist: focal
language: go
go: 1.14
branches:
  only:
    - master
    - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"
    - "/^deploy-test/"

addons:
  apt:
    packages:
      - upx-ucl

env:
  global:
    - CGO_ENABLED=0

install:
  - go build -ldflags="-s -w" ./cmd/gh-pr-comment
  - go build -ldflags="-s -w" ./cmd/gh-pr-upload
  - upx ./gh-pr-comment
  - upx ./gh-pr-upload
  - sudo cp ./gh-pr-comment /usr/local/bin/
  - sudo cp ./gh-pr-upload /usr/local/bin/

script:
  - go vet ./...
  - go test ./...
  - .ci/upload-test.sh
  - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config

before_deploy:
  - export GITHUB_TOKEN=${GITHUB_TOKEN_DEPLOY}

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
