language: go
go: 1.14
os:
  - linux
  - macos
dist: bionic
jobs:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    - os: macos
branches:
  only:
    - master
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+/"

addons:
  apt:
    packages:
      - upx-ucl

env:
  global:
    - CGO_ENABLED=0

install:
  - go build -ldflags="-s -w" ./cmd/gh-pr-comment
  - go build -ldflags="-s -w" ./cmd/gh-pr-upload
  - upx ./gh-pr-comment
  - upx ./gh-pr-upload
  - sudo cp ./gh-pr-comment /usr/local/bin/
  - sudo cp ./gh-pr-upload /usr/local/bin/

script:
  # Go test
  - go vet ./...
  - go test ./...
  # E2E test
  - .ci/upload-test.sh
  # GoReleaser config check
  - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config
  # Test install script
  - ./install
  - test -x ${HOME}/.local/bin/gh-pr-comment
  - test -x ${HOME}/.local/bin/gh-pr-upload

before_deploy:
  - export GITHUB_TOKEN=${GITHUB_TOKEN_DEPLOY}

deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
