language: go
dist: bionic
go: 1.14
branches:
  only:
    - master

script:
  # Go test
  - go vet ./...
  - go test ./...
  # E2E test
  - .ci/upload-test.sh "Travis-CI ${TRAVIS_OS_NAME} ${TRAVIS_CPU_ARCH}"
