name: release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GPG_FINGERPRINT: "358B DF63 B4AE D76A 871A  E62E 1BF1 686B 468C 35B2"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Load signing key
        run: echo "${{ secrets.PGP_SIGN_KEY }}" | gpg --import --no-tty --batch
      - name: Sign installer scripts
        run: |
          for file in install.sh env.sh
          do
            gpg \
              --batch \
              --no-tty \
              --passphrase="${{ secrets.SIGN_KEY_PASSPHRESE }}" \
              --pinentry-mode=loopback \
              --local-user="${GPG_FINGERPRINT}" \
              --output="${file}.sig" \
              --detach-sign \
              ${file}
          done
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          SIGN_KEY_PASSPHRESE: ${{ secrets.SIGN_KEY_PASSPHRESE }}
