name: test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Post comment
        run: go run ./cmd/gh-pr-comment "Test from GitHub Actions" "Comment from GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
