name: test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Test
        run: |
          go vet ./...
          go test ./...
      - name: Post comment
        run: bash .ci/upload-test.sh "GitHub Actions ${{ runner.os }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install script test
        if: runner.os != 'Windows'
        run: |
          ./install.sh
          test -x ${HOME}/.local/bin/gh-pr-comment
          test -x ${HOME}/.local/bin/gh-pr-upload
      - name: Check GoReleaser
        if: runner.os == 'Linux'
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
